# Generated by Django 4.0 on 2022-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='finished_voca',
            new_name='finished_collection_voca',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='voca',
            new_name='finished_user_voca',
        ),
        migrations.AddField(
            model_name='user',
            name='user_voca',
            field=models.TextField(blank=True),
        ),
    ]
