# Generated by Django 4.0.1 on 2022-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('users', '0002_rename_finished_voca_user_finished_collection_voca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collection',
        ),
        migrations.AddField(
            model_name='user',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection', to='words.Word'),
        ),
    ]
