# Generated by Django 4.0.1 on 2022-01-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_finished_voca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='finished_voca',
            field=models.JSONField(default='[]', null=True),
        ),
    ]
