# Generated by Django 4.0.1 on 2022-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.JSONField(default=[]),
        ),
    ]
