# Generated by Django 4.0 on 2022-01-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('userBoards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userboard',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user'),
        ),
    ]
