# Generated by Django 4.0.1 on 2022-01-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaBoards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaboard',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
