# Generated by Django 4.0.1 on 2022-01-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaBoards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaboard',
            name='writer',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
