# Generated by Django 4.0.1 on 2022-02-06 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnaBoards', '0004_remove_qnaboard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaboard',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wirter', to=settings.AUTH_USER_MODEL),
        ),
    ]
